// accordionData.js
export const accordionData = [
  {
    title: "Section 1",
    content: [
      { topic: "Preview", time: "03:44" },
      { topic: "Course Resources", time: "00:38" },
      { topic: "Preview", time: "04:13" },
      { topic: "Link to Original Bitcoin White Paper", time: "00:07" },
      { topic: "Interfacing with Ethereum Networks", time: "03:14" },
      { topic: "Updated Metamask Setup for new UI", time: "00:38" },
      { topic: "Metamask Setup", time: "05:09" },
      { topic: "Ethereum Accounts", time: "05:22" },
      { topic: "Getting Test Ether to Use in the Course", time: "02:07" },
      { topic: "What's a Transaction?", time: "07:43" },
      { topic: "Why'd We Wait?", time: "05:00" },
      { topic: "A Quick Note About the Next Lecture", time: "00:16" },
      { topic: "Basic Blockchains", time: "17:49" },
      { topic: "Block Time", time: "10:49" },
      { topic: "Smart Contracts", time: "06:55" },
      { topic: "The Solidity Programming Language", time: "05:03" },
      {
        topic: "Updated Remix Instructions for new UI - Do Not Skip",
        time: "00:37",
      },
      { topic: "Our First Contract", time: "05:41" },
      { topic: "Contract Structure", time: "05:39" },
      { topic: "Function Declarations", time: "08:59" },
      { topic: "Deploying Contract in New Remix UI", time: "00:29" },
      { topic: "Testing with Remix", time: "10:57" },
      { topic: "Redeploying Contracts", time: "02:34" },
      { topic: "Behind the Scenes of Deployment", time: "05:43" },
      {
        topic: "More on Running Functions Than You Want to Know",
        time: "14:15",
      },
      { topic: "Wei vs Ether", time: "04:07" },
      { topic: "Gas and Transactions", time: "11:24" },
      { topic: "Mnemonic Phrases", time: "11:28" },
      { topic: "We Need More Test Ether!", time: "01:03" },
      {
        topic: "Obtaining More Test Ether from Recommended Faucet",
        time: "02:04",
      },
    ],
  },
  {
    title: "Section 2",
    content: [
      { topic: "Installing Node.js, npm and Git", time: "00:57" },
      { topic: "Contract Deployment", time: "05:31" },
      { topic: "Completed Boilerplate", time: "01:11" },
      { topic: "Project Requirements", time: "05:09" },
      { topic: "Project File Walkthrough", time: "04:32" },
      { topic: "Compiling Solidity", time: "06:22" },
      {
        topic: "Invalid asm.js or Constructor Deprecation Warning",
        time: "00:23",
      },
      { topic: "The Compile Script", time: "06:09" },
      { topic: "Testing Architecture", time: "03:48" },
      { topic: "Breaking Change - Web3 v4 and Ganache", time: "00:41" },
      { topic: "Installing Modules", time: "04:15" },
      { topic: "Web3 Versioning", time: "04:18" },
      { topic: "Web3 Providers", time: "04:47" },
      { topic: "Testing with Mocha", time: "18:16" },
      { topic: "Mocha Structure", time: "04:44" },
      { topic: "Fetching Accounts from Ganache", time: "06:43" },
      { topic: "Refactor to Async/Await", time: "02:39" },
      { topic: "Deployment with Web3", time: "06:11" },
      { topic: "Deployed Inbox Overview", time: "11:18" },
      { topic: "Asserting Deployment", time: "05:22" },
      { topic: "Verifying the Initial Message", time: "08:25" },
      { topic: "Testing Message Updates", time: "06:24" },
      { topic: "Deployment with Infura", time: "06:57" },
      { topic: "Infura Signup", time: "00:59" },
      {
        topic: "Super Important Note about Seed / Recovery Phrase Security",
        time: "00:32",
      },
      { topic: "Wallet Provider Setup", time: "06:40" },
      { topic: "Deployment to Testnet", time: "07:21" },
      { topic: "Observing Deployment on Etherscan", time: "04:51" },
      { topic: "Remix Permissions and Metamask", time: "00:24" },
      { topic: "Deployed Contracts in Remix", time: "07:13" },
      { topic: "Project Review", time: "09:27" },
      { topic: "Updating Your Inbox Project to Solc v0.8.9", time: "" },
    ],
  },
  {
    title: "Section 3",
    content: [
      { topic: "The Lottery Contract", time: "02:36" },
      { topic: "Lottery Design", time: "02:49" },
      { topic: "Reminder on Updated Remix UI", time: "00:10" },
      { topic: "Basic Solidity Types", time: "09:43" },
      { topic: "Starting the Lottery Contract", time: "04:44" },
      { topic: "The Message Global Variable", time: "05:53" },
      { topic: "Overview of Arrays", time: "11:06" },
      { topic: "Overview of Mappings and Structs", time: "03:42" },
      { topic: "Big Solidity Gotcha", time: "06:28" },
      { topic: "Entering the Lottery", time: "03:57" },
      { topic: "Validation with Require Statements", time: "09:48" },
      { topic: "The Remix Debugger", time: "04:03" },
      { topic: "Pseudo Random Number Generator", time: "10:34" },
      { topic: "Selecting a Winner", time: "04:58" },
      { topic: "Sending Ether from Contracts", time: "05:08" },
      { topic: "Resetting Contract State", time: "04:07" },
      { topic: "Requiring Managers", time: "05:03" },
      { topic: "Function Modifiers", time: "06:18" },
      { topic: "Returning Players Array", time: "02:13" },
      { topic: "Contract Review", time: "02:51" },
      { topic: "Completed Boilerplate - Do Not Skip", time: "00:13" },
      { topic: "New Test Setup", time: "03:04" },
      { topic: "Test Project Updates", time: "02:04" },
      { topic: "Web3 v4 and Ganache Breaking Change Reminder", time: "00:16" },
      { topic: "Test Helper Review", time: "04:33" },
      { topic: "Asserting Deployment", time: "02:54" },
      { topic: "Entering the Lottery", time: "06:27" },
      { topic: "Asserting Multiple Players", time: "02:39" },
      { topic: "Try-Catch Assertions", time: "05:57" },
      { topic: "Testing Function Modifiers", time: "03:29" },
      { topic: "End to End Test", time: "11:04" },
      // ... (other topics for Section 3)
    ],
  },
  {
    title: "Section 4",
    content: [
      { topic: "The Lottery Contract", time: "02:36" },
      { topic: "Lottery Design", time: "02:49" },
      { topic: "Reminder on Updated Remix UI", time: "00:10" },
    ],
  },
  {
    title: "Section 5",
    content: [
      { topic: "The Lottery Contract", time: "02:36" },
      { topic: "Lottery Design", time: "02:49" },
      { topic: "Reminder on Updated Remix UI", time: "00:10" },
    ],
  },
  {
    title: "Section 6",
    content: [
      { topic: "The Lottery Contract", time: "02:36" },
      { topic: "Lottery Design", time: "02:49" },
      { topic: "Reminder on Updated Remix UI", time: "00:10" },
    ],
  },
  // Add more sections as needed
];
